### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Sompatbu** [yahoo/CaffeOnSpark#121] opened 2016-07-22 05:21 UTC
I've follow the build instruction and found this while execute the make build command

> cd caffe-public; make proto; make -j4 -e distribute; cd ..
> make[1]: Entering directory `/home/piyaphat/CaffeOnSpark/caffe-public'
> make[1]: Nothing to be done for`proto'.
> make[1]: Leaving directory `/home/piyaphat/CaffeOnSpark/caffe-public'
> make[1]: Entering directory`/home/piyaphat/CaffeOnSpark/caffe-public'
> # add proto
> 
> cp -r src/caffe/proto distribute/
> # add include
> 
> cp -r include distribute/
> mkdir -p distribute/include/caffe/proto
> cp .build_release/src/caffe/proto/caffe.pb.h distribute/include/caffe/proto
> # add tool and example binaries
> 
> cp .build_release/tools/net_speed_benchmark.bin .build_release/tools/convert_imageset.bin .build_release/tools/upgrade_net_proto_binary.bin .build_release/tools/caffe.bin .build_release/tools/train_net.bin .build_release/tools/device_query.bin .build_release/tools/extract_features.bin .build_release/tools/compute_image_mean.bin .build_release/tools/upgrade_solver_proto_text.bin .build_release/tools/test_net.bin .build_release/tools/finetune_net.bin .build_release/tools/upgrade_net_proto_text.bin distribute/bin
> cp .build_release/examples/cpp_classification/classification.bin .build_release/examples/siamese/convert_mnist_siamese_data.bin .build_release/examples/mnist/convert_mnist_data.bin .build_release/examples/cifar10/convert_cifar_data.bin distribute/bin
> # add libraries
> 
> cp .build_release/lib/libcaffe.a distribute/lib
> install -m 644 .build_release/lib/libcaffe.so.1.0.0-rc3 distribute/lib
> cd distribute/lib; rm -f libcaffe.so;   ln -s libcaffe.so.1.0.0-rc3 libcaffe.so
> # add python - it's not the standard way, indeed...
> 
> cp -r python distribute/python
> make[1]: Leaving directory `/home/piyaphat/CaffeOnSpark/caffe-public'
> export LD_LIBRARY_PATH="/usr/local/cuda-7.5/lib64:/home/piyaphat/CaffeOnSpark/caffe-public/distribute/lib:/home/piyaphat/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn -B package -DskipTests
> /bin/sh: 1: mvn: not found
> make: **\* [build] Error 127

any suggestion?

Ps. sorry I don't know how to not prevent markdown styling.

**Comment by GnosisYu** [comment] 2016-07-22 16:24
I think your error was caused by no mvn or maven installed on your machine.

**Comment by arundasan91** [comment] 2016-07-26 03:11
Hello,

In order to show the terminal output properly you can use three of these tick's    `   together.

``` It will make the text in this format ```

Now to help you, I see that `maven` is not installed in your system.

Try 

1. `sudo apt-get install maven`
2. Go to `CaffeOnSpark` root directory and type `make clean`
3. In redo `make build` in `CaffeOnSpark` root directory.

Please let me know if it helped.

Also make sure that your `Makefile.config` is properly configured.

Thanks, 
Arun

**Comment by mriduljain** [comment] 2016-11-29 06:25
No update, closing this. Reopen if required

**Closed by mriduljain** 2016-11-29 06:25 UTC
