### ISSUE TITLE
Can run train mnist example on YARN (NPE)

### ISSUE THREAD

**Issue by dumoulma** [yahoo/CaffeOnSpark#144] opened 2016-09-01 09:47 UTC
Hi!
I've got the latest code. I know for sure caffe can run on all my nodes, it's tested and works fine. I'm running on g2.2xlarge EC2 instances. Spark version is 1.6.1, with 4 nodes.
I've copied the compiled project (which compiled with zero issues on the first try) to all nodes in the same location.

command used to launch the job:
```
spark-submit --master yarn --deploy-mode cluster \
>     --num-executors ${SPARK_WORKER_INSTANCES} \
>     --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt \
>     --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
>     --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
>     --class com.yahoo.ml.caffe.CaffeOnSpark  \
>     ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
>         -train \
>         -features accuracy,loss -label label \
>         -conf lenet_memory_solver.prototxt \
>         -devices ${DEVICES} \
>     -connection ethernet \
>         -model hdfs:///mnist.model \
>         -output hdfs:///mnist_features_result
```
the environment variables are all defined:
```
LD_LIBRARY_PATH=/opt/CaffeOnSpark/caffe-public/distribute/lib:/opt/CaffeOnSpark/caffe-distri/distribute/lib:/usr/local/cuda-7.5/lib64
CAFFE_ON_SPARK=/opt/CaffeOnSpark
DEVICES=1
SPARK_WORKER_INSTANCES=3
```
The permissions on hdfs (actually mapr-fs) are OK for the user "mapr". the source files are where they are suggested in the yarn wiki page.
```
[mapr@ip-10-0-0-84 centos]$ hadoop fs -ls -R hdfs:/projects/machine_learning/image_dataset/
drwxr-xr-x   - mapr mapr          2 2016-09-01 09:00 hdfs:///projects/machine_learning/image_dataset/cifar10_test_lmdb
-rwxr-xr-x   3 mapr mapr   41218048 2016-09-01 09:00 hdfs:///projects/machine_learning/image_dataset/cifar10_test_lmdb/data.mdb
-rwxr-xr-x   3 mapr mapr       8192 2016-09-01 09:00 hdfs:///projects/machine_learning/image_dataset/cifar10_test_lmdb/lock.mdb
drwxr-xr-x   - mapr mapr          2 2016-09-01 09:00 hdfs:///projects/machine_learning/image_dataset/cifar10_train_lmdb
-rwxr-xr-x   3 mapr mapr  206032896 2016-09-01 09:00 hdfs:///projects/machine_learning/image_dataset/cifar10_train_lmdb/data.mdb
-rwxr-xr-x   3 mapr mapr       8192 2016-09-01 09:00 hdfs:///projects/machine_learning/image_dataset/cifar10_train_lmdb/lock.mdb
drwxr-xr-x   - mapr mapr          2 2016-09-01 08:59 hdfs:///projects/machine_learning/image_dataset/mnist_test_lmdb
-rwxr-xr-x   3 mapr mapr   10338304 2016-09-01 08:59 hdfs:///projects/machine_learning/image_dataset/mnist_test_lmdb/data.mdb
-rwxr-xr-x   3 mapr mapr       8192 2016-09-01 08:59 hdfs:///projects/machine_learning/image_dataset/mnist_test_lmdb/lock.mdb
drwxr-xr-x   - mapr mapr          2 2016-09-01 08:59 hdfs:///projects/machine_learning/image_dataset/mnist_train_lmdb
-rwxr-xr-x   3 mapr mapr   61763584 2016-09-01 08:59 hdfs:///projects/machine_learning/image_dataset/mnist_train_lmdb/data.mdb
-rwxr-xr-x   3 mapr mapr       8192 2016-09-01 08:59 hdfs:///projects/machine_learning/image_dataset/mnist_train_lmdb/lock.mdb
```
I've also verified spark works in yarn mode by running successfully the example SparkPi in yarn mode.

The Error I get is a NPE:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/mapr/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tmp/hadoop-mapr/nm-local-dir/usercache/mapr/filecache/24/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
16/09/01 09:35:31 WARN SQLContext: Overriding shared prefixes property:
old value - com.mysql.jdbc,org.postgresql,com.microsoft.sqlserver,oracle.jdbc,com.mapr.fs.shim.LibraryLoader,com.mapr.security.JNISecurity,com.mapr.fs.jni,
new value - com.mysql.jdbc,org.postgresql,com.microsoft.sqlserver,oracle.jdbc,com.mapr.security.JNISecurity,com.mapr.fs.jni
16/09/01 09:35:32 ERROR ApplicationMaster: User class threw exception: java.lang.NullPointerException
java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:114)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:114)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.yahoo.ml.caffe.LmdbRDD.localLMDBFile(LmdbRDD.scala:186)
	at com.yahoo.ml.caffe.LmdbRDD.com$yahoo$ml$caffe$LmdbRDD$$openDB(LmdbRDD.scala:203)
	at com.yahoo.ml.caffe.LmdbRDD.getPartitions(LmdbRDD.scala:47)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1157)
	at com.yahoo.ml.caffe.CaffeOnSpark.trainWithValidation(CaffeOnSpark.scala:271)
	at com.yahoo.ml.caffe.CaffeOnSpark$.main(CaffeOnSpark.scala:56)
	at com.yahoo.ml.caffe.CaffeOnSpark.main(CaffeOnSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:542)
```
I'm running out of ideas to fix this... any suggestions are much appreciated!!

**Comment by anfeng** [comment] 2016-09-02 23:39
Your problem is likely caused by a bug in CaffeOnSpark. The issue should
have been fixed with latest PRs (#141 - #146).
EC2 guide has also been updated with new AMI.

Please let us know if you still have problem.

Andy

Andy

**Comment by dumoulma** [comment] 2016-09-03 09:25
I have recompiled and it's not generating the NPE anymore.  thanks for the quick response, it's very much appreciated.

Now I'm getting trouble with LMDB complaining of IO error  but I think I'm not defining my paths correctly. the local path files are OK I think. I figure I can mess around with it a bit more and get that figured out.

the file: lenet_memory_train_test.prototxt needs to be changed to reflect new input paths, the default values aren't correct for my environment for the source of train and test after all. 

Should it be local or hadoop fs paths, to run the MNIST example? I haven't used CaffeOnSpark for a while and I didn't keep the previous instances so I don't remember anymore... I'm guessing it's

**Comment by anfeng** [comment] 2016-09-03 14:49
Please provide the complete HDFS path for training and test Lmdb files.

Andy Feng

**Comment by dumoulma** [comment] 2016-09-15 08:26
I can confirm that the latest code does indeed work now. Thanks a lot for your support Andy.

**Closed** 2016-09-15 08:27 UTC
